### PR TITLE
Adding foreign code extractors for spark sql and exporting required classes

### PR DESCRIPTION
**Pull request by skbitsp**
Adding foreign code extractors for spark sql and exporting required classes

### CODE REVIEW

**Comment by krassowski** [comment]
@skbitsp can you please rebase to trigger the CI checks which were re-enabled on the 4.x branch by https://github.com/jupyter-lsp/jupyterlab-lsp/pull/982?

**Comment by skbitsp** [comment]
> @skbitsp can you please rebase to trigger the CI checks which were re-enabled on the 4.x branch by #982?
Done ✅.

**Comment by skbitsp** [comment]
Hi, actually our team is working on a timeframed project, merging this PR would really help us, so could I please get an estimated timeframe of when it would be merged?

**Comment by krassowski** [comment]
Merging itself is not a problem, but since the tests are failing it would take some manual checks to do a release. You can help by fixing up `CI / jstest/lint` which needs simple fixes on typing in Python. Otherwise I will merge when I get to backporting the CI fixes after releasing a new version.

**Comment by skbitsp** [comment]
Okay, I was checking the jstest/lint test, it fails at this: "python_packages/jupyter_lsp/jupyter_lsp/manager.py:64: error: Incompatible types in assignment (expression has type "Bool[bool, Union[bool, int]]", variable has type "bool")  [assignment]"

This PR doesn't make any changes to that file

**Comment by skbitsp** [comment]
If this will take time, I can also explore taking a clone of the repo and making a custom deployment for our company's internal usage. But every MP can only publish one version. Since this one has server extension as well as Jupyter lab extension, and there's some code duplication also amongst the two extensions.. is there a clear segregation bw the code so that we can create multiple mps?

**Comment by krassowski** [comment]
> This PR doesn't make any changes to that file, so not sure how to fix it without changing the existing code

I pushed a few commits, but if you are asking for an ASAP release of an older version, it would help if you could contribute towards reducing the maintenance burden ([we all like puppies](https://github.com/jupyterlab/jupyterlab/blob/main/CORPORATE.md)) and yes it involves changing existing code.

**Comment by krassowski** [comment]
Now the lint job is failing only on the code that you did modify ;)

```
$ prettier --check "**/*{.ts,.tsx,.js,.jsx,.css,.json,.md,.yml}"
Checking formatting...
[warn] packages/jupyterlab-lsp/src/index.ts
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

**Comment by skbitsp** [comment]
oops ;) 
Prettified all the problematic files now

**Comment by skbitsp** [comment]
All the prettify checks pass on my machine now:
```
prettier --check "**/*{.ts,.tsx,.js,.jsx,.css,.json,.md,.yml}"
Checking formatting...
All matched files use Prettier code style!
```

**Comment by krassowski** [comment]
It seems you have a different version of `prettier` installed or different settings are being picked up. Force-pushing after discarding df14ca283d618cf51d3cbd0ae2716e7ab1826b95 commit should be enough to make CI pass.

**Comment by skbitsp** [comment]
Done ✅

**Comment by skbitsp** [comment]
Thank you so much for merging :) 
Will this automatically produce a release version or are there any additional steps?

**Comment by krassowski** [comment]
[v4.3.0](https://github.com/jupyter-lsp/jupyterlab-lsp/releases/tag/v4.3.0) is out [on PyPI](https://pypi.org/project/jupyterlab-lsp/4.3.0/) and [on npm](https://www.npmjs.com/package/@jupyter-lsp/jupyterlab-lsp/v/4.3.0). The next step would be forward-porting the spark sql extractors (opening a PR against main branch) if you wish them to be included in future releases (5.0+) too.

**Pull request merged**
