### PR TITLE
Update `script` for `typescript-language-server`

### PR DESCRIPTION
**Pull request by jtpio**
## References

Looking into using `typescript-language-server` and following the [docs to install it](https://jupyterlab-lsp.readthedocs.io/en/latest/Language%20Servers.html#example-getting-all-the-node-js-based-language-servers), it looks like `jupyter_lsp` was not able to find the language server:

image

Updating the script seems to be fixing it:

image

## Code changes

Update the `script` for `typescript-language-server`.

## User-facing changes

Users can install and use `typescript-language-server` with JupyterLab LSP.

## Backwards-incompatible changes

This supports the latest version of `typescript-language-server`, but might break previous versions when the file was still `cli.js`?

## Chores

- [ ] linted 
- [ ] tested 
- [ ] documented 
- [ ] changelog entry

### CODE REVIEW

**Comment by krassowski** [comment]
The test failures are relevant. It looks the location of the binary entry point has changed last year and we are pinning to an old version. I think we should bump the version, but also consider using the [`bin` field from `package.json`](https://github.com/typescript-language-server/typescript-language-server/blob/b224b878652438bcdd639137a6b1d1a6630129e4/package.json#L18-L20).

**Comment by jtpio** [comment]
> I think we should bump the version

Done in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/1064/commits/f014c9e9aaf58cc37e7c3b5abfd455f31d0e12a8 :+1: 



> but also consider using the [`bin` field from `package.json`](https://github.com/typescript-language-server/typescript-language-server/blob/b224b878652438bcdd639137a6b1d1a6630129e4/package.json#L18-L20).

That makes sense, although there might be several scripts available, and the name might not match the name of the module itself?  I guess this would apply to other specs derived from `NodeModuleSpec`, so maybe something to track in a separate issue?

**Comment by jtpio** [comment]
> maybe something to track in a separate issue?

Opened https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1066

**Review by krassowski — APPROVED** [review]
Thanks @jtpio and thanks for opening the issue!

**Comment by krassowski** [comment]
@jtpio this is available in jupyter-lsp 2.2.4 - thanks again!

**Pull request merged**
