### PR TITLE
[wip] Add Robot Framework language server

### LINKED ISSUE #332: Support/test a Robot Framework language server
## Elevator Pitch

Adding support for autodetecting a robot framework language server

## Motivation

- [robotframework-lsp](https://pypi.org/project/robotframework-lsp) has shipped a couple solid versions, and has a product built around it
  - the [conda-forge](https://github.com/conda-forge/staged-recipes/pull/12548) process has been started
- we have lots of examples, and this would increase our ability to dogfood diverse languages in building this code

## Design Ideas

- add to environment
- add spec
- add tests, etc.
- add robotframemework [syntax mode](https://github.com/robots-from-jupyter/robotkernel/tree/master/src/jupyterlab_robotmode)
  - it's part of `robotkernel`, which we _could_ choose to add to the development environment
  - i'm pretty much the original author of that syntax mode, and owe an update for some of the new syntax  (some for loop stuff isn't handled correctly), but it basically works, today

### PR DESCRIPTION
**Pull request by bollwyvl**
[Binder](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-lsp/add-robot-server?urlpath=lab%2Ftree%2Fatest%2Fexamples%2Fexample.robot)

## References

- fixes #332 with `robotframework-lsp`, which is generally available on `pypi` and `conda-forge`
- also adding
  - `jupyterlab_robotmode` for robot syntax highlighting
  - `robotkernel` as it has a number of nice bells and whistles for browser-based testing
    - `xeus-robot` is _also_ very cool, as it works with the debugger, which we need to start considering
      - but I think we want a separate PR that adds all the `xeus` stuff in one go, as they are most likely to conflict with each other
        - e.g. `xeus-python`, `xeus-sql`, `xeus-robot`, etc.

## Code changes

- [x] add `robotframework-lsp` in a number of places (_not_ lint, though!)
  - [ ] if we find ourselves wanting to use robot notebooks, we can figure out an `nblint` plugin or something 
- [x] the robotframework 4.0 release is coming up... there might be some version adventures between releases, have pinned for the time being to avoid surprises.
- [ ] validate that [spec](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/ext/jupyter_lsp.py) that `robotframework-lsp` ships :tada:  works  
  - [ ] we're better off upstreaming a PR than claiming support for one with tweaks
- [x] add editor robot tests
- [ ] add notebook robot tests

## User-facing changes

- Users should see nicer integration with robot files and notebooks
  - will demo on our Binder for looking at/running _our_ tests, which is cute
    - browser screenshots _can_ be made to work
      - might need to add `apt.txt` (or stuff it, and use a `Dockerfile`)... binder's getting a bit unwieldy

## Backwards-incompatible changes

- N/A

## Chores

- [x] linted
- [x] tested
- [x] documented
- [x] changelog entry

### CODE REVIEW

**Comment by bollwyvl** [comment]
Ahh, `rflsp` isn't compatible with python 3.6. Knew this day would come.

**Comment by bollwyvl** [comment]
Woof... the vendored watchdog is going nuts on my setup... will push so we have something to look at in CI/binder, but something's definitely not right:

```py
lsp: 2021-01-24 15:14:18 UTC pid: 159268 - MainThread - EXCEPTION - robocorp_ls_core.jsonrpc.endpoint
Failed to handle request 0

Traceback (most recent call last):
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/jsonrpc/endpoint.py", line 142, in consume
    self._handle_request(
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/jsonrpc/endpoint.py", line 278, in _handle_request
    handler_result = handler(params)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/jsonrpc/dispatchers.py", line 38, in handler
    return method(**(params or {}))
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/python_ls.py", line 261, in m_initialize
    self.workspace = self._create_workspace(rootUri, workspaceFolders or [])
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/server_api/server.py", line 83, in _create_workspace
    return RobotWorkspace(
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/impl/robot_workspace.py", line 18, in __init__
    Workspace.__init__(self, root_uri, workspace_folders=workspace_folders)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/workspace.py", line 265, in __init__
    self.add_folder(folder)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/impl/robot_workspace.py", line 24, in add_folder
    self.libspec_manager.add_workspace_folder(folder.uri)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/impl/libspec_manager.py", line 544, in add_workspace_folder
    folder_info.start_watch(self._observer, self._file_changes_notifier)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/impl/libspec_manager.py", line 260, in start_watch
    self._watch = observer.notify_on_any_change(
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/watchdog_wrapper.py", line 223, in notify_on_any_change
    self._observer.schedule(
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/api.py", line 301, in schedule
    emitter.start()
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify_c.py", line 201, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify_c.py", line 398, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify_c.py", line 412, in _add_watch
    Inotify._raise_error()
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/libs/watchdog_lib/watchdog/observers/inotify_c.py", line 424, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
lsp: 2021-01-24 15:14:18 UTC pid: 159268 - MainThread - EXCEPTION - robocorp_ls_core.python_ls
Error updating document: {'uri': 'file://~/jupyterlab-lsp/atest/examples/example.robot', 'version': 0} with changes: [{'text': '*** Settings ***\nLibrary           SeleniumLibrary\nLibrary           Builtin\n\n*** Variables ***\n${ABC}            abc\n\n*** Keywords ***\nSpecial Log\n    [Arguments]    ${log}\n    [Documentation]    a special log\n    Log    ${log.upper()}!\n\n*** Test Cases ***\nLog Something\n    Special Log    ${ABC}\n\n'}]

Traceback (most recent call last):
  File "~/envs/default/lib/python3.8/site-packages/robotframework_ls/vendored/robocorp_ls_core/python_ls.py", line 318, in m_text_document__did_change
    self.workspace.update_document(
AttributeError: 'NoneType' object has no attribute 'update_document'
lsp: 2021-01-24 15:14:18 UTC pid: 159268 - MainThread - EXCEPTION - robocorp_ls_core.python_ls
Error updating document: {'uri': 'file://~/jupyterlab-lsp/atest/examples/example.robot', 'version': 1} with changes: [{'text': '*** Settings ***\nLibrary           SeleniumLibrary\nLibrary           Builtin\n\n*** Variables ***\n${ABC}            abc\n\n*** Keywords ***\nSpecial Log\n    [Arguments]    ${log}\n    [Documentation]    a special log\n    Log    ${log.upper()}!\n\n*** Test Cases ***\nLog Something\n    Special Log    ${ABC}\n\n'}]


```

**Comment by bollwyvl** [comment]
Looks like _some_ changes were made upstream on rflsp, so _maybe_ this will work now?

Of note, it doesn't support a _ton_ of [features that intersect](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/robotframework_ls_impl.py#L209-L248) with ours... but it's something.

**Comment by bollwyvl** [comment]
Nope :(

**Comment by bollwyvl** [comment]
Worth another shot in a couple hours...
https://github.com/conda-forge/robotframework-lsp-feedstock/pull/14

**Comment by bollwyvl** [comment]
Working on warming this back up, and getting the new, more-maintained (than `rflint`) `robocop` up, which will be nice to have for our code anyway.

**Comment by bollwyvl** [comment]
Gah, i've made a proper mess of things, here. I think given the increasing complexity of the py36/37 stuff, it's time to look at doing an up-front job (or committing) lockfiles with `conda-lock`.


Basically, the YML in `requirements` would look more like:

```yaml
requirements/
  - _base.yml  # what's needed in _every_ env
  - build.yml
  - lint.yml
  - test.yml
  - test-3.6.yml
  - test-3.7.yml
  - test-3.8.yml
  - test-3.9.yml
```

And permute across these things to yield:

```yaml
.github/
  - locks/
    - build-3.9-linux-64.conda.lock
    - lint-3.9-linux-64.conda.lock
    - test-3.6-linux-64.conda.lock
    # ...
    - test-3.9-windows-64.conda.lock
```

Then all of the jobs would just use their respective lockfile in `environment-file`.

The advantage to checking them in is we'd save the couple minutes up-front of doing the resolve, and have them around for local review. But the danger then becomes if we get lazy with our locks: we've actually found a number of regressions on upstream things by mostly sticking to the bleeding edge... maybe we'd just have one or two jobs that were canary-like.

**Comment by krassowski** [comment]
Should we just add the spec for robotframework-lsp and mark it editor support only or partial support to make it more discoverable? I know that `pip install robotframework-lsp` just works, but it's not in the docs.

**Comment by bollwyvl** [comment]
Oy! I should definitely warm this back up. rflsp really supports a lot of lsp features now, and should feel really nice. 

If we're dropping py 3.6 in #718 , that will make this easier, so i may well re-start from a clean slate.

**Comment by krassowski** [comment]
Closing as superseded by #724. Thank you!

**Pull request closed without merging**
