### PR TITLE
Add notebook dependency to CI to test `serverextension`, fix CI

### PR DESCRIPTION
**Pull request by krassowski**
An attempt to fix CI failure seen in #867

### CODE REVIEW

**Comment by krassowski** [comment]
The lint failure is due to robottidy changing `Test Tags` to `Force Tags` (https://github.com/MarketSquare/robotframework-tidy/issues/432) and then robocop complaining that it should be the other way. Nothing to do other than wait for a release upstream.

**Comment by bollwyvl** [comment]
The individual rule could be relaxed for now...

**Comment by krassowski** [comment]
Kicking CI since the new release is already available and on conda-forge (thanks for a quick merge @bollwyvl).

**Comment by krassowski** [comment]
bash language server failures are gone (I did suspect this was an intermittent issue, waiting helped), but now MacOS smoke fails with cryptic:

```
+ jupyter labextension list
/Users/runner/work/_temp/03c846b0-ddaa-4fd7-be26-b0a115a5b859.sh: line 2: jupyter: command not found
```

but `pip list` shows all jupyter dependencies fine. I know we can workaround, but it sounds like an upstream problem again. Does it ring a bell?

This constant CI flake is really burning out energy.

**Comment by bollwyvl** [comment]
Perhaps try `python3 -m jupyter`?

Maybe some new `jupyter_core` path vulnerability fallout? 

There is still the option of pinning the dependencies down harder with e.g. `conda-lock` so that handling issues like this can be a more intentional, single-purpose PR, if possible.

**Comment by bollwyvl** [comment]
It may also be worth upgrading the various `setup-*` actions to the latest versions, as things outside our control definitely _will_ break in some places soon.

**Comment by krassowski** [comment]
I will experiment in https://github.com/krassowski/jupyterlab-lsp/pull/3

**Comment by bollwyvl** [comment]
Perhaps this:
```robot
css:button[title="Refresh File List"]
```
Could be pointed at the more stable:

```robot
css:button[data-command="filebrowser:refresh"]
```

**Comment by bollwyvl** [comment]
```
Evaluating expression '__import__("urllib.request").request.urlopen("http://localhost:38635/@est/api/shutdown?token=jGIubKOf", data=[])' failed: URLError: <urlopen error [Errno 111] Connection refused>
```

This feels almost certainly related to the `jupyter_core` change, and might be [fixable here](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/atest/Keywords.resource#L43):

```robot
Create Notebok Server Config
    # ...
    ${conf} =    Set Variable    ${NOTEBOOK DIR}${/}${JPSERVER CONF JSON}
    Set Environment Variable
    ...    name=JUPYTER_CONFIG_DIR
    ...    value=${NOTEBOOK DIR}
```

**Review by bollwyvl — APPROVED** [review]

**Pull request merged**
